### ISSUE TITLE
Sorting and filtering not working when using search class

### ISSUE THREAD

**Issue by ghost** [Fosome/garb#10]
example 1:

  class Exits
    include Garb::Resource
    metrics :pageviews, :exits
    dimensions :request_uri
  end

  pp Exits.results(profile) do
    filter :exits.gte => 100
    sort :exits.desc
  end

 it gave wrong result (not sorted, not filtred):
 [#<OpenStruct pageviews="767", exits="150", request_uri="/">,
  #<OpenStruct pageviews="276", exits="42", request_uri="/atrakcje.html">]

but when i do:

 report = Garb::Report.new(profile, :limit => 2)
 report.metrics :pageviews, :exits
 report.dimensions :request_uri
 report.filter :exits.gte => 100
 report.sort :exits.desc
 pp report.results

 result is correct:

 [#<OpenStruct pageviews="563", exits="172", request_uri="/galeria.html">,
  #<OpenStruct pageviews="767", exits="150", request_uri="/">]

did i do something wrong or it's a bug ?

**Comment by tpitale** [comment]
Can you please provide a gist with the code, the issues interface makes it unclear what is going on.

**Comment by tpitale** [comment]
I can't seem to reproduce this, so I'll close the ticket for now.
