### ISSUE TITLE
Authentication type should just be "GOOGLE"

### ISSUE THREAD

**Issue by hisham** [Fosome/garb#12]
In authentication_request.rb, the parameter 'accountType' should be 'GOOGLE', not 'HOSTED_OR_GOOGLE'.

This will make this library work with Google Apps hosted emails that also have an Analytics account (or else Google will log me in the hosted "gmail" account, rather than the "google" analytics account).

So just change the accountType to "GOOGLE" or allow me to pass a parameter to do so...

**Comment by tpitale** [comment]
And what about those people that don't have both, that just have HOSTED type accounts? These accounts can be given access to analytics, last time I checked. We chose the current parameter because we felt it matched 80% need, and kept a configuration option out. I will see if I can add something, though.

**Comment by hisham** [comment]
That's me..I have a hosted account, but once you give it access to analytics, you are making a GOOGLE version of the account as well. You can even have two different passwords for the accounts.

So from people's perspective, they're two distinct accounts, and the only one that works with Analytics is the GOOGLE one. 

I did discover from a comment here that if you change the account type to "GOOGLE_OR_HOSTED", then thinks will work, since Google will first try to log you into your google account before the hosted account...

I hope this makes sense. So what I recommend is you change the account type from "HOSTED_OR_GOOGLE" to "GOOGLE_OR_HOSTED". I made this change on my machine and now I can use my 'hosted' account to make GA API calls.

**Comment by tpitale** [comment]
We chose the current parameter for the reasons you describe. If you can point out in the docs where this is, or has changed, I'll be happy to change it.

**Comment by cypriss** [comment]
I also have this problem.  I have a hosted account, but my analytics are in a google account.  same login for both.
The login method should take a third optional argument, the account type.  It can default to whatever you want.

**Comment by tpitale** [comment]
I'll make this an option in 0.3.0 which should be out soon.

**Comment by tpitale** [comment]
New version of garb supports this option. http://gemcutter.org/gems/garb

I'll update the documentation with an example shortly.

**Comment by kobezt08** [comment]
Hi, I'm getting the following issue "No Analytics account was found for the currently logged-in user" even thought I have specified account_type => "GOOGLE". Only when i manual going into authenticate_request.rb and change teh default to "GOOGLE_OR_HOSTED" then i'm able to get the output out

**Comment by tpitale** [comment]
It's a setting, use GOOGLE_OR_HOSTED as the :account_type. Be sure to use 0.3.1 from gemcutter.
