### ISSUE TITLE
invalid namespace

### ISSUE THREAD

**Issue by atsuhiro** [Fosome/garb#13]
http://schemas.google.com/dataexport/2009
↓
http://schemas.google.com/analytics/2009

**Comment by tpitale** [comment]
Are you getting an error? From what I see in Google's documentation, there are two namespaces.

**Comment by tpitale** [comment]
I'm finally seeing this manifesting in no data being parsed by happymapper. I'll fix and release this asap.

**Comment by tpitale** [comment]
Version 0.3.0 fixes this issue. http://gemcutter.org/gems/garb
