### ISSUE TITLE
Still experiencing issue with AccountType

### ISSUE THREAD

**Issue by kobezt08** [Fosome/garb#15]

**Comment by kobezt08** [comment]
Experiencing "No Analytics account was found for the currently logged-in user" even though i specified account_type as GOOGLE. It will only work when i go into authenticate_request.rb and change the default to GOOGLE_OR_HOSTED

**Comment by kobezt08** [comment]
at times i will receive "Unknown action. No action responded to analytics. Actions: access_denied, current_user, current_user_session, home, redirect_back_or_default, require_login, require_login_with_notice, require_no_user, sitemap, and store_location"

**Comment by tpitale** [comment]
Are you using 0.3.1? GOOGLE_OR_HOSTED can be passed to :account_type.
