### ISSUE TITLE
undefined method `desc' for :exit_rate:Symbol 

### ISSUE THREAD

**Issue by angelf** [Fosome/garb#18]
Running the example found in the Wiki:

  report.sort :exit_rate.desc

I get the error

   undefined method `desc' for :exit_rate:Symbol

This is on ruby 1.8.7.

Thanks for the library!

**Comment by tpitale** [comment]
Sorry about that. I'm working with DataMapper and MongoMapper to remove conflicts with symbol operators. Until I get that worked out, desc is missing from the latest version of Garb.

**Comment by angelf** [comment]
ok, no problem

I have a simple stupid patch that implements the feature with the syntax:

report.sort "exit_rate.desc"

do you want me to upload it to github and send a pull request?

**Comment by tpitale** [comment]
No, that's alright. Thanks though. I should have this fixed soon.

**Comment by tpitale** [comment]
Just an update: both MongoMapper and Garb now use a unified SymbolOperator to prevent conflicts. I should have this added to DataMapper soon enough, and I'll be ready to push out a new gem for Garb.

**Comment by tpitale** [comment]
This should be fixed in the latest gem.

**Comment by angelf** [comment]
great - thanks a lot!
