### ISSUE TITLE
results returning as array, not openstruct or hash

### ISSUE THREAD

**Issue by rob-mcgrail** [Fosome/garb#23]
I seem to be getting arrays for my results, rather than an ostruct.

Example:

```
class Reports

  def things
    report = Garb::Report.new($profile)
    report.metrics :pageviews
    thing = report.results
```

_snip_
    puts thing.pageviews => in `things': undefined method`pageviews' for [#<OpenStruct pageviews="10">]:Array (NoMethodError)

```
puts report.results.inspect  => [#<OpenStruct pageviews="10">]

puts thing => #<OpenStruct pageviews="10">

puts thing[0] => #<OpenStruct pageviews="10">
```

Sorry new to ruby and reporting this sort of thing - apologies if this is an obvious error on my part, or if this is the wrong way to report.

**Comment by tpitale** [comment]
Nope, this is a fine channel. It's not very often that only one result is returned. The typical pattern after getting results is to simply use #each to get an individual object with the pageviews (in this case) that you want. For example:

<pre><code>report.results.each {|result| puts result.pageviews}</pre></code>

Good luck!
