### ISSUE TITLE
0.7.4 errors on empty results

### ISSUE THREAD

**Issue by tpitale** [Fosome/garb#25]
I tried to get a report for a campaign that does not exist.
In 0.7.2 the result was just an empty array (which I think is good),
The new version results in the following error when I try to get the results:

You have a nil object when you didn't expect it!
You might have expected an instance of ActiveRecord::Base.
The error occurred while evaluating nil.[]
/var/lib/gems/1.8/gems/garb-0.7.4/lib/garb/report_response.rb:30:in values_for' /var/lib/gems/1.8/gems/garb-0.7.4/lib/garb/report_response.rb:30:in map' /var/lib/gems/1.8/gems/garb-0.7.4/lib/garb/report_response.rb:30:in values_for' /var/lib/gems/1.8/gems/garb-0.7.4/lib/garb/report_response.rb:16:in parse' /var/lib/gems/1.8/gems/garb-0.7.4/lib/garb/report_response.rb:15:in map' /var/lib/gems/1.8/gems/garb-0.7.4/lib/garb/report_response.rb:15:in parse' /var/lib/gems/1.8/gems/garb-0.7.4/lib/garb/report_response.rb:10:in results' /var/lib/gems/1.8/gems/garb-0.7.4/lib/garb/resource.rb:54:in results

**Comment by bpmiller** [comment]
i have the same problem

**Comment by tpitale** [comment]
Alright, I'm on this one. I'll have something out soon. Sorry about this folks!

**Comment by tpitale** [comment]
Commit is in HEAD. Will release shortly.
