### ISSUE TITLE
NoMethodError: undefined method `string' for XMLParser:Class

### ISSUE THREAD

**Issue by paulsingh** [Fosome/garb#26]
I'm able to successfully create a Garb::Session but then I run into a problem:

> > Garb::Account.all
> > NoMethodError: undefined method `string' for XMLParser:Class
> >     from /Library/Ruby/Gems/1.8/gems/happymapper-0.3.0/lib/happymapper.rb:75:in`parse'
> >     from /Library/Ruby/Gems/1.8/gems/garb-0.7.0/lib/garb/profile.rb:50:in `all'
> >     from /Library/Ruby/Gems/1.8/gems/garb-0.7.0/lib/garb/account.rb:14:in`all'
> >     from (irb):2

I can't, for the life of me, figure out when this started occurring and/or how to start debugging. Any help?

**Comment by tpitale** [comment]
Have you tried the latest version? It no longer required happymapper, which has a lot of problems with libxml2 (c library). It now uses another jnunemaker gem: crack.

If that doesn't work, I would recommend looking into reinstall libxml2.

**Comment by paulsingh** [comment]
Ah, yep - upgrading to 0.7.4 solved the issue. Sorry guys!

**Comment by tpitale** [comment]
Great, glad it helped.
