### ISSUE TITLE
Custom segments support?

### ISSUE THREAD

**Issue by rob-mcgrail** [Fosome/garb#27]
Hi - thanks for a great gem - been using this in my first programming attempt ever, and it's been going well.

However, I got sent some new requests for my script, that I can only picture working (nicely) if I use segments.

The API feed query exporter allows me to use these like this:

segment=gaid::95904094

But a search through the GARB source and docs makes me think there's no support for this in GARB - is this right?

In either case, cheers for your work; and for answering what I can now see was a pretty obvious question a few months back...

**Comment by tpitale** [comment]
Thanks. Sadly, I haven't added support for segments (and a few other "advanced" features) just yet. Either because they haven't been added to the export API or because I haven't yet had time to add them.

I'll take a quick look and see what the deal is, and go from there.

**Comment by tpitale** [comment]
Okay, did some research and I'll add this ASAP.

http://code.google.com/apis/analytics/docs/gdata/gdataReferenceDataFeed.html#segment

**Comment by tpitale** [comment]
Also useful in that segments come back as part of accounts: http://code.google.com/apis/analytics/docs/gdata/gdataReferenceAccountFeed.html#accountResponse

**Comment by assaf** [comment]
+1 for segments.

**Comment by rob-mcgrail** [comment]
Yeah thanks for keeping this in your todos - this will save me a lot of filter-related pain, or python porting, over the next couple of months :D

**Comment by tpitale** [comment]
Okay, this requires making the switch to GData version 2. I'm working on it, but it may take a bit of time. This will be version 0.8. Hopefully I'll get goals from profiles in 0.8.1 or something like that.

**Comment by tpitale** [comment]
Silly Google has changed the concept of profile to be an account, and removed profiles. Ugh.

**Comment by tpitale** [comment]
To get the useful part to you guys sooner I'm just going to add the reporting side of things. This will allow for setting the segment id used but won't let you get back a list of the segments available for a profile, yet.

That okay for now?

**Comment by tpitale** [comment]
Garb 0.7.5 allows you to set the segment id for a report. I'll update the wiki in a minute.

**Comment by rob-mcgrail** [comment]
That's great for me - thanks heaps.
