### ISSUE TITLE
Security: SSL certificate validation

### ISSUE THREAD

**Issue by pepawel** [Fosome/garb#3]
This line is not very nice from a security standpoint:
http://github.com/vigetlabs/garb/blob/4437f9941791043c869b942c5524c7c4e9fcd5e4/lib/garb/authentication_request.rb#L29

Should be:

<pre>
http.verify_mode = OpenSSL::SSL::VERIFY_PEER
store = OpenSSL::X509::Store.new
store.set_default_paths
http.cert_store = store
</pre>

**Comment by tpitale** [comment]
Never got this working in the past because, for whatever reason, the ssl cert would not be authentic from google. To get around this and use verify peer you have to download    http://curl.haxx.se/ca/cacert.pem and then login with Garb::Session.login(username, password, :secure => true)
