### ISSUE TITLE
Add full support for the account feed in the API - with ability to list goals for a profile

### ISSUE THREAD

**Issue by rgrieselhuber** [Fosome/garb#34]
The AccountFeed provides more data than is currently accessible with Garb. I personally have a need to list all of the goals (and relevant attributes) configured for each account and / or profile.

Here is a full list of the data available:

http://code.google.com/apis/analytics/docs/gdata/gdataReferenceAccountFeed.html

**Comment by tpitale** [comment]
@rgrieselhuber: what info do you need from the goals? I just committed the listing of goals on a profile, without destination or step information (just name, value, and active flag). I'll keep working on it, but if you want to check out master that would be a help.

**Comment by rgrieselhuber** [comment]
Great, thanks very much! For now, I just need those fields. Eventually I might need the other information available in that feed (eg. destination, segment info.) but this will help quite a bit. 

I'll check out the master and let you know if anything pops out. Thanks again.

**Comment by tpitale** [comment]
Master now has destination and step information. Let me know if I missed anything. I'll release a gem if everything checks out.

**Comment by rgrieselhuber** [comment]
Very cool. Sorry I've been behind in checking on this. I need to wrap up a few things this week and I'll try to check everything on Monday.

**Comment by tpitale** [comment]
The new Management API is complete and will be released with Garb 0.9.0. I'm in the process of updating the documentation around this.

**Comment by rgrieselhuber** [comment]
This is great, thanks very much.
