### ISSUE TITLE
Multiple filters don't work with OAuth

### ISSUE THREAD

**Issue by stephenlewis** [Fosome/garb#35]
The following code results in a 401 (Unknown authorization header) from GA, but works fine when using Garb::Session.login. The problem seems to be fixed by 32c3eb603f5f1cca321ed78c3e33187b9c6e8e47.

(You'll need to set 'token' and 'secret' to run the code below, but it should otherwise work as-is.)

I suspect that the problem is that the OAuth gem is not escaping semicolons when constructing the canonical URL, but Google are escaping them when checking the signature - this explains why we only trip up when there are semicolons in the URL (for example when using multiple filters).

```
#!/usr/bin/env ruby

require 'rubygems'
require 'oauth'
require 'garb'

consumer = OAuth::Consumer.new('anonymous', 'anonymous', {
  :site => 'https://www.google.com',
})

Garb::Session.access_token = OAuth::AccessToken.new(consumer, token, secret)

profile = Garb::Account.all.first.profiles.first

class Visits
  extend Garb::Resource

  metrics :visits

  filters do
    contains(:keyword, 'your')
    eql(:medium, 'cpc')
  end
end

results = Visits.results(profile)
```

**Comment by tpitale** [comment]
Thanks, I'll take a look asap!

**Comment by tpitale** [comment]
I've done some research and it appears to be a problem with the OAuth gem. Other people have mentioned the problem. Converting ';' to '%3B' does fix the problem but seems like a hack. I'll do more digging to see if I can't fix the underlying problem.

**Comment by tpitale** [comment]
This appears to have no end in sight, I've release a version of Garb with %3B and nobody has reported other issues. Closing this ticket and sticking with the hack around oauth.
