### ISSUE TITLE
'default page' for a profile

### ISSUE THREAD

**Issue by foreverman** [Fosome/garb#36]
Hey,

First, thanks for all the contributors to garb, it is very helpful for integration with google analytics. I have a need to query to 'default page' setting(https://www.google.com/support/googleanalytics/bin/answer.py?answer=32995&hl=en_US) for a profile, so is there anyway to get it from garb?

Thanks.

Sean

**Comment by tpitale** [comment]
This data is not available as part of the analytics API at this point. The only chance is that the Management API will make it available at some point. Sorry.
