### ISSUE TITLE
Get an invalid gem format error attempting to install rubygem

### ISSUE THREAD

**Issue by knaveofdiamonds** [Fosome/garb#37]
Trying to install the gem, I get:

```
ERROR:  Error installing garb:
    invalid gem format for /opt/local/lib/ruby/gems/1.8/cache/garb-0.7.6.gem
```

My environment is OSX 10.6, ruby 1.8.7-174, rubygems 1.3.6. Any ideas?

**Comment by tpitale** [comment]
Please try 0.8.0.

**Comment by tpitale** [comment]
Are you still experiencing this problem?

**Comment by knaveofdiamonds** [comment]
No - this seems to be fine now.

Thanks!
