### ISSUE TITLE
Support proxy access

### ISSUE THREAD

**Issue by andymatsubara** [Fosome/garb#38]
I hope Garb support access under proxy server.

**Comment by boudewijnv** [comment]
Here's a solution, can something like this be patched? 

add to:
garb.rb (line 32):

def get_proxy
   http_proxy = ENV["http_proxy"]
   URI.parse(http_proxy) rescue nil
  end

change:
authentication_request.rb (28):
      http = Net::HTTP.new(uri.host, uri.port, Garb.get_proxy.host, Garb.get_proxy.port)

data_request.rb (33):
      http = Net::HTTP.new(uri.host, uri.port, Garb.get_proxy.host, Garb.get_proxy.port)

**Comment by tpitale** [comment]
If you fork and patch I'll consider merging, but this seems like an edge case and I have no way of testing.
