### ISSUE TITLE
undefined method `camelize' for "goal"

### ISSUE THREAD

**Issue by danieljohnmorris** [Fosome/garb#42]
Hey, I can authenticate ok, but get the following error when I try to access the Account or Profile features. Any ideas?

/Users/dan/.rvm/gems/ruby-1.8.7-p174/gems/garb-0.7.6/lib/garb.rb:36:in `to_ga': undefined method`camelize' for "goal":String (NoMethodError)
    from /Users/dan/.rvm/gems/ruby-1.8.7-p174/gems/garb-0.7.6/lib/garb/profile.rb:12:in `initialize'
    from /Users/dan/.rvm/gems/ruby-1.8.7-p174/gems/garb-0.7.6/lib/garb/profile.rb:24:in`new'
    from /Users/dan/.rvm/gems/ruby-1.8.7-p174/gems/garb-0.7.6/lib/garb/profile.rb:24:in `all'
    from /Users/dan/.rvm/gems/ruby-1.8.7-p174/gems/garb-0.7.6/lib/garb/profile.rb:24:in`map'
    from /Users/dan/.rvm/gems/ruby-1.8.7-p174/gems/garb-0.7.6/lib/garb/profile.rb:24:in `all'
    from /Users/dan/.rvm/gems/ruby-1.8.7-p174/gems/garb-0.7.6/lib/garb/profile.rb:28:in`first'

**Comment by tpitale** [comment]
This was an AS3 bug based on faulty requirements. Fixed in 0.8.0. Sorry.
