### ISSUE TITLE
NoMethodError for gmail account without any google analytics accounts

### ISSUE THREAD

**Issue by foreverman** [Fosome/garb#47]
Hey,

'NoMethodError' was thrown when I tried to call Garb::Profile.all(no google analytics account in my gmail account), the following is the code used to access google analytics data:

access_token, access_secret = user.access_tokens.last
Garb::Session.access_token = OAuth::AccessToken.new(GoogleAuth.consumer, access_token, access_secret)
profiles = Garb::Profile.all

And here is the backtrace:

from /Users/bob/.rvm/gems/ruby-1.8.7-p249/gems/garb-0.8.4/lib/garb/profile.rb:10:in `initialize'
    from /Users/bob/.rvm/gems/ruby-1.8.7-p249/gems/garb-0.8.4/lib/garb/profile.rb:25:in`new'
    from /Users/bob/.rvm/gems/ruby-1.8.7-p249/gems/garb-0.8.4/lib/garb/profile.rb:25:in `all'
    from /Users/bob/.rvm/gems/ruby-1.8.7-p249/gems/garb-0.8.4/lib/garb/profile.rb:25:in`map'
    from /Users/bob/.rvm/gems/ruby-1.8.7-p249/gems/garb-0.8.4/lib/garb/profile.rb:25:in `all'

I think we need to return an empty array if there are no any google analytics accounts.

Thanks.

Sean

**Comment by tpitale** [comment]
This will be fixed when I complete the new management api updates. The reason this fails is most likely in trying to construct accounts and profiles from the results. I'll close this ticket when the new api updates are out.

**Comment by tpitale** [comment]
The new management API is complete and will be released soon with 0.9.0. Please check it out as I update the documentation. Thanks!
