### ISSUE TITLE
Filter throws exception when used in class context

### ISSUE THREAD

**Issue by pepawel** [Fosome/garb#5]
<pre>
class Something
  include Garb::Resource
  filter :page_path.contains => /test/
end
</pre>

gives:

<pre>
NoMethodError: You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.<<
    from /usr/lib/ruby/gems/1.8/gems/vigetlabs-garb-0.2.1/lib/garb/resource.rb:23:in `filter'
</pre>

**Comment by tpitale** [comment]
Yes, filter and sort can only be used within the block while getting results. I have yet to decide how I'd like to handle filters on the class (probably have a default_filters method).
