### ISSUE TITLE
Report results bleed on classes

### ISSUE THREAD

**Issue by kneath** [Fosome/garb#50]
This may seem confusing, but it resulted in much more confusion on my end, so hopefully it makes sense.  When you use `extend Garb::Model` and call results, these results bleed across multiple results calls with different filters.

I had this code:

```
module BrowserUsage

  class BrowserName
    extend Garb::Model
    dimensions :browser
    metrics :visits
  end

  class BrowserVersion
    extend Garb::Model
    dimensions :browser_version
    metrics :visits
  end

  def self.browser_name_results(profile)
    BrowserName.results(profile)
  end

  def self.browser_version_results(profile, browser)
    BrowserVersion.results(profile) do
      filters :browser.eql(:browser, browser)
    end
  end
end
```

When calling `BrowserUsage.browser_version_results(profile, 'Firefox')` and then calling `BrowserUsage.browser_version_results(profile, 'Safari')` — you'll end up with the same amount of visits on both result sets.

I've fixed this locally by just using the one-off reports that now work (yay!), but it's something that definitely made me pretty confused trying to figure out why my data was wrong.

**Comment by tpitale** [comment]
This is definitely a documentation problem, though it does indicate a problem that exists in the Garb::Resource ("deprecated" way). The motivation of the new Garb::Model is to pass the filters to the results method (similar to #all in AR). The reason you're getting the same results is that the block with the filters is ignored.

This is probably what you're looking for: https://gist.github.com/e8f52f2113ec8b484137

I hope this helps!

I'll leave this ticket open until I can update the documentation.

**Comment by tpitale** [comment]
The README has been updated with the basic example of metrics/dimensions/filtering. The wiki is soon to follow. Closing this ticket now.
