### ISSUE TITLE
README demonstrates deprecated classes (Garb::Report instead of Garb::Model)

### ISSUE THREAD

**Issue by jimgreer** [Fosome/garb#51]

**Comment by tpitale** [comment]
Yes. The documentation is in need of lots of updates. I'm still trying to finalize Garb::Model and then I will update all of it. Any suggestions of what you would like to see documented would be appreciated, or documentation itself.

**Comment by tpitale** [comment]
The README has been updated, and the wiki will be shortly. Closing now.
