### ISSUE TITLE
Both garb and mongoid add methods Symbol

### ISSUE THREAD

**Issue by matthewford** [Fosome/garb#54]
This is causing some odd conflicts, is there another way to specify :visits.desc without using the method on symbol?

**Comment by tpitale** [comment]
Not right now, you can try :visits.descending since this probably will not conflict. MongoMapper and Garb have an agreed upon method for use symbol operators. I'll try to speak with Mongoid, still working on DataMapper.

**Comment by matthewford** [comment]
:visits.descending I believe is also defined

**Comment by tpitale** [comment]
Darn, then I'll have to speak with those guys soon.
