### ISSUE TITLE
Error in feed parsing when only one profile is available (ruby 1.9.2)

### ISSUE THREAD

**Issue by arambert** [Fosome/garb#56]
When there is only one profile available for a session, parsed_response['feed']['entry'] is a hash and not an array of hashes.
Array.new do transform this hash to an array (at least in ruby 1.9.2) and this triggers an Exception in parse_link (Exception: You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.detect)
I suggest to use [] instead of Array.new(): this way the hash is not transformed to an array and everything works fine.
--- Suggestion of Solution --- Tested with ruby 1.9.2 ---
in Garb::Management::Feed
    def entries
      # possible to have nil entries, yuck
     parsed_response ? [parsed_response['feed']['entry']].flatten.compact : []

**Comment by tpitale** [comment]
Thanks, I'll look into this today.

**Comment by tpitale** [comment]
Changes pushed to master, making a gem soon.
