### ISSUE TITLE
Some characters should be escaped in filters expressions

### ISSUE THREAD

**Issue by arambert** [Fosome/garb#57]
if you try to filter with a url including a comma (ex: /stuff-1,-wearing) you will get the following exception: 

```
A Garb::DataRequest::ClientError occurred in xxx:

"<errors xmlns='http://schemas.google.com/g/2005'><error><domain>GData</domain><code>InvalidRequestUriException</code><internalReason>Malformed filter syntax: -wearing</internalReason></error></errors>"
 garb (0.9.0) lib/garb/data_request.rb:27:in `send_request'
```

In fact commas (,), semicolons (;), backslash () should be escaped (\, \; \) (see http://code.google.com/intl/fr/apis/analytics/docs/gdata/gdataReferenceDataFeed.html#filters)

---- Suggestion of modification ----
    in Garb::FilterParameters
    def to_params
      value = self.parameters.map do |param|
        param.map do |k,v|
          next unless k.is_a?(SymbolOperator)
          "#{URI.encode(k.to_google_analytics, /[=<>]/)}#{CGI::escape(v.to_s.gsub(/,|;|\/){|c| '\'+c})}"
        end.join('%3B') # Hash AND (no duplicate keys), escape char for ';' fixes oauth
      end.join(',') # Array OR

```
  value.empty? ? {} : {'filters' => value}
end
```

---

**Comment by tpitale** [comment]
Another great catch, thanks!

**Comment by tpitale** [comment]
Changes pushed to master, making a gem soon.

**Comment by arambert** [comment]
great news, thanks !!!
