### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by amnwebmaster** [Fosome/garb#60]
Filters do not appear to be working correctly on either metrics or dimensions - as a simple example the following query included OpenStruct visits="7834", hostname="record.net.au" in the results. I've tried using several other dimension and metric combinations which didn't work. Thanks for the great work!

Garb::Report.new(profile, {
                       :metrics => [:visits],
                       :dimensions => [:hostname],
                       :filters => {:hostname.does_not_match => 'record.net.au'}
                       }).results

**Comment by tpitale** [comment]
Thanks for making this a separate issue.

The usage of Report is incorrect, and also deprecated. Filters are not passed as options to initialize the report.

Try https://gist.github.com/783915

**Comment by tpitale** [comment]
I would also recommend updating to the latest garb and trying out Garb::Model.

Best of luck.
