### ISSUE TITLE
Filter with ORs in Garb::Model 

### ISSUE THREAD

**Issue by arambert** [Fosome/garb#62]
Is it possible ?
When i use :filters => [{filter1}, {filter2}]
the method parse_filters adds options[:filters] to filters.parameters as a single filter in the filters array. The global filter becomes [ [{filter1}, {filter2}] ](which is not an array of hashes... so no filter is applied)

--- Suggestion of solution ---

```
 def parse_filters(options)
      filters = FilterParameters.new
      filters.parameters << options[:filters] if options.has_key?(:filters)
      filters
 end
```

should maybe be replaced by

```
 def parse_filters(options)
    filters = ::Garb::FilterParameters.new
    if options.has_key?(:filters)
      filters.parameters << options[:filters] if options[:filters].is_a?(Hash)
      filters.parameters += options[:filters] if options[:filters].is_a?(Array)
    end
    filters
 end
```

**Comment by tpitale** [comment]
Yeah, the filtering sorta sucks right now. Evidence of this can be found in almost any ORM. I'm still wracking my brain to come up with a solution.

However, I will look into this, and at least document the proper usage. AND/OR did work at some point.

**Comment by tpitale** [comment]
This is now fixed in master. Thanks for bringing it up.
