### ISSUE TITLE
Simple examples that work

### ISSUE THREAD

**Issue by deplorableword** [Fosome/garb#63]
Hi,

I followed some links from the viget blog, but it looks like you've changed the syntax from the examples posted there?

Any chance you could throw some simple and complete examples in the wiki that return data, I'm having a hard time getting the Exits or any of the examples in the blog posts working. 

Cheers

**Comment by tomaadland** [comment]
Same here. I tried the simplest one in console after creating a session with oauth i ran: 
Garb::Management::Account.all to get a list of all the profiles. 
The result is: ga:accountId
NoMethodError: undefined method `underscore' for "accountId":String

If I could get this to work i'm sure it's a great gem. 

Thanks, 

Tom

**Comment by tpitale** [comment]
All of the examples in the wiki work for me. Do you have something specific that you tried that didn't work? What is the backtrace? Is there something specific you are trying to do?

**Comment by abhinavrastogi** [comment]
I am trying a simple code:

require 'garb'
Garb::Session.login('username','pass')
Garb::Management::Profile.all.detect {|profile| profile.web_property_id == 'UA-XXXXXX-XX'}

and I am getting the errors:
You don't have i18n installed in your application. Please add it to your Gemfile and run bundle install
/usr/lib64/ruby/gems/1.8/gems/garb-0.9.1/lib/garb.rb:58:in `from_ga': undefined method`underscore' for "accountId":String (NoMethodError)

I am very new to Ruby and can't understand how to fix it! Please help!
