### ISSUE TITLE
Timeout:Error (rbuf_fill)

### ISSUE THREAD

**Issue by rgrieselhuber** [Fosome/garb#64]
I'm getting this error fairly frequently:

```
Timeout::Error: execution expired
from /opt/ruby/lib/ruby/1.8/timeout.rb:60:in `rbuf_fill'
from /opt/ruby/lib/ruby/1.8/net/protocol.rb:134:in `rbuf_fill'
from /opt/ruby/lib/ruby/1.8/net/protocol.rb:116:in `readuntil'
from /opt/ruby/lib/ruby/1.8/net/protocol.rb:126:in `readline'
from /opt/ruby/lib/ruby/1.8/net/http.rb:2024:in `read_status_line'
from /opt/ruby/lib/ruby/1.8/net/http.rb:2013:in `read_new'
from /opt/ruby/lib/ruby/1.8/net/http.rb:1050:in `__request__'
from /opt/ruby/lib/ruby/gems/1.8/gems/rest-client-1.6.1/lib/restclient/net_http_ext.rb:17:in `request'
from /opt/ruby/lib/ruby/1.8/net/http.rb:1037:in `__request__'
from /opt/ruby/lib/ruby/1.8/net/http.rb:543:in `start'
from /opt/ruby/lib/ruby/1.8/net/http.rb:1035:in `__request__'
from /opt/ruby/lib/ruby/gems/1.8/gems/rest-client-1.6.1/lib/restclient/net_http_ext.rb:17:in `request'
from /opt/ruby/lib/ruby/gems/1.8/gems/oauth-0.4.1/lib/oauth/consumer.rb:164:in `request'
from /opt/ruby/lib/ruby/gems/1.8/gems/oauth-0.4.1/lib/oauth/tokens/consumer_token.rb:25:in `request'
from /opt/ruby/lib/ruby/gems/1.8/gems/oauth-0.4.1/lib/oauth/tokens/access_token.rb:11:in `request'
from /opt/ruby/lib/ruby/gems/1.8/gems/oauth-0.4.1/lib/oauth/tokens/access_token.rb:24:in `get'
from /opt/ruby/lib/ruby/gems/1.8/gems/garb-0.8.0/lib/garb/data_request.rb:39:in `oauth_user_request'
from /opt/ruby/lib/ruby/gems/1.8/gems/garb-0.8.0/lib/garb/data_request.rb:24:in `send_request'
from /opt/ruby/lib/ruby/gems/1.8/gems/garb-0.8.0/lib/garb/account_feed_request.rb:10:in `response'
from /opt/ruby/lib/ruby/gems/1.8/gems/garb-0.8.0/lib/garb/account_feed_request.rb:14:in `parsed_response'
from /opt/ruby/lib/ruby/gems/1.8/gems/garb-0.8.0/lib/garb/account_feed_request.rb:18:in `entries'
from /opt/ruby/lib/ruby/gems/1.8/gems/garb-0.8.0/lib/garb/profile.rb:24:in `all'
```

Have you seen this? I remember seeing this before but can't remember if there was a resolution. 

Thanks!

Ray

**Comment by tpitale** [comment]
This may be something in the version of ruby or the version of oauth. Do you have the latest patch level for 1.8?

**Comment by chrisle** [comment]
I'm also seeing this.  Using ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0].  Is there a way to increase the time limit?

**Comment by tpitale** [comment]
Sadly, this does not appear to be within my control.

I'm not sure if it will help, but try the latest oauth 0.4.4 and the latest ruby 1.8.7 (patch 330). RVM is a huge help in this regard.

**Comment by chrisle** [comment]
I added one line that adjusts the timeout to Net::HTTP.  It seemed to have solve the problem.  I will experiment with it more to see if it actually solved it for good.  If it has, I'll report back and possibly submit a patch for review.

# garb-0.9.1/lib/garb/data_request.rb

# starting at line 31:

```
def single_user_request
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true
  http.read_timeout = 120 # force the timeout to be 2 minutes!
  http.verify_mode = OpenSSL::SSL::VERIFY_NONE
  http.get("#{uri.path}#{query_string}", {'Authorization' => "GoogleLogin auth=#{@session.auth_token}", 'GData-Version' => '2'})
end
```

**Comment by rgrieselhuber** [comment]
This issue is listed as closed -- does this resolve it? Was it submitted as a patch?

**Comment by chrisle** [comment]
Unfortunately adding timeout gave me less timeout errors, but I was still timing out.  I had read that it was more a problem with timeout in Ruby than Net:HTTP or Garb.  I instead used begin/recover to manage long timeouts instead.

**Comment by tpitale** [comment]
The fact that you're seeing timeout errors may be a smell. I wonder if it's simply taking too long for google to return the results you're looking for. If I'm going to add a patch I would add the ability to pass some option down from Higher in Garb as opposed to blindly increasing the read timeout.

If somebody wants this as a feature, please open a new issue as a feature request and I will see when I can get to it.

**Comment by rgrieselhuber** [comment]
I think that's what the problem is - Google Analytics is taking a very long time to respond in many cases. I'll add the feature request now.

**Comment by chrisle** [comment]
It probably is.  I can tell you that the accounts I'm using have a lot of profiles, goals, and segments.  I agree it would be good to have something that passes an argument instead of what I did.  Mainly I did it to see if the problem was Google or something else.

**Comment by ojacobson** [comment]
I've put together [a patch](https://github.com/vigetlabs/garb/pull/88) that addresses this by disabling the read_timeout entirely.
