### ISSUE TITLE
Regexp in filters is broken in 0.9.1

### ISSUE THREAD

**Issue by pepawel** [Fosome/garb#65]
Hi,

Here is faulty commit:
https://github.com/vigetlabs/garb/commit/48173c2db10497072830c1df60d15694d3af49a2

Escaping backslash character makes using regular expresions like for example "\d" impossible.

**Comment by tpitale** [comment]
The backslash is a reserved character in the API. The commit corrected previously incorrect behavior. http://code.google.com/apis/analytics/docs/gdata/gdataReferenceDataFeed.html#filters

**Comment by pepawel** [comment]
I believe backslash needs to be escaped only if user wants to treat it like a normal character. The fact is escaping backslash in regular expression breaks it. Not escaping it makes regular expresions work.

I think the document you've provided is just wrong. I know it is official, but look here:

http://code.google.com/apis/analytics/docs/gdata/gdataExplorer.html?filters=ga%253Acity%253D~%255Cd&start-date=2011-02-09&end-date=2011-02-23&max-results=50

It is a tool made by Google. Notice the "\d" in filters is not backslash-escaped. It is only url encoded.
