### ISSUE TITLE
start_date

### ISSUE THREAD

**Issue by ghost** [Fosome/garb#66]
Hello, 

Great little gem. I am using the start_date as follows:

profile.views(:start_date => 1.year.ago, :filters => {:page_path.eql => some_url})

and no matter what I do, it yields a 30 day pull. Is this option supported?

I am using garb 0.9.1

The only thing I could come up with is that end_date must be set, as well, or maybe it has to be included in the :filters hash... Help please.

nato

**Comment by tpitale** [comment]
Yes, it always does 30 days from the start_date. To get a longer period, you must use both start and end date.

**Comment by ghost** [comment]
tpitale,

Great. I assumed there was something small I was missing. Thanks for supporting your gem with such considerable speed.

nato
