### ISSUE TITLE
sort desc?

### ISSUE THREAD

**Issue by tsailipu** [Fosome/garb#69]
Have you thought about including the ability to specify desc sort?  I like being to specify :limit, but not being able to specify the sorting direction limits the usefulness of :limit...

(BTW, I think the default report examples such as Visits are all out of date?)

**Comment by tpitale** [comment]
:field.desc or :field.descending should work.

**Comment by jasperkennis** [comment]
I've tried this, but it doesn't seem to work. Has this changed?

**Comment by romikoops** [comment]
I found overlapping issue related with conflict with 'origin' gem. So, I just put this code as workaround:

``` ruby
# Workaround for overlapping by other Ruby gems
class Symbol
  [:descending, :desc].each do |meth|
    define_method(meth) { SymbolOperator.new(self, meth) } if method_defined?(meth)
  end
end
```
