### ISSUE TITLE
Getting this error when running garb

### ISSUE THREAD

**Issue by tzooming** [Fosome/garb#70]
i got the error below when I was trying to get  GA API data after obtaining the access_token from the signet gem (for google analytics). Error was for line 3. Can you help? thansk

1.access_token = session[:token]
2.Garb::Session.access_token = access_token
3.@profile = Garb::Management::Profile.all 

NoMethodError in OauthgaController#index

private method `get' called for "1/2txxxxxxaccess_token_from signet":String

**Comment by tpitale** [comment]
The access token has to been an actually OAuth access token, not just a string.
