### ISSUE TITLE
Add longer timeouts to deal with slow response time from Google Analytics

### ISSUE THREAD

**Issue by rgrieselhuber** [Fosome/garb#71]
In reference to this issue: https://github.com/vigetlabs/garb/issues/64/

The Google Analytics is frequently slow to respond to requests and the default timeout does not allow requests to complete. This feature would allow API calls via Garb to wait longer for GA to respond.

**Comment by tpitale** [comment]
I've investigated having this as a setting, simply making it longer is not really ideal.

**Comment by tpitale** [comment]
I've made another ticket to add this as a setting, that will be implemented soon.
