### ISSUE TITLE
Unable to fetch profiles ? (302 This document has moved)

### ISSUE THREAD

**Issue by arambert** [Fosome/garb#75]
This may not be Garb specific but anyway if you get this problem too, you should know that there is a thread there http://code.google.com/intl/en/apis/analytics/groups/managementApiGroup.html?place=topic%2Fgoogle-analytics-management-api%2Fz_S3OHHfmd0%2Fdiscussion
Edit:
the new correct link: http://code.google.com/intl/en/apis/analytics/community/managementApiGroup.html?place=topic%2Fgoogle-analytics-management-api%2Fz_S3OHHfmd0%2Fdiscussion

**Comment by tpitale** [comment]
The link seems broken, and I've not seen anyone else comment. If it becomes an issue I will make a wiki page.
