### ISSUE TITLE
goals unavailable in 0.9.*

### ISSUE THREAD

**Issue by seanhussey** [Fosome/garb#76]
I'm trying to migrate from version 0.7.6 to 0.9.1.  Once I get the profile in 0.7.6, calling profile.goals gives me the goals.  In 0.9.1, using the same credentials, I get this:

```
profile.goals
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/sean/.rvm/gems/ree-1.8.7-2010.02@new-garb/gems/garb-0.9.1/lib/garb/management/goal.rb:36:in `properties='
from /Users/sean/.rvm/gems/ree-1.8.7-2010.02@new-garb/gems/garb-0.9.1/lib/garb/management/goal.rb:31:in `new_from_entry'
from /Users/sean/.rvm/gems/ree-1.8.7-2010.02@new-garb/gems/garb-0.9.1/lib/garb/management/goal.rb:12:in `all'
from /Users/sean/.rvm/gems/ree-1.8.7-2010.02@new-garb/gems/garb-0.9.1/lib/garb/management/goal.rb:12:in `map'
from /Users/sean/.rvm/gems/ree-1.8.7-2010.02@new-garb/gems/garb-0.9.1/lib/garb/management/goal.rb:12:in `all'
from /Users/sean/.rvm/gems/ree-1.8.7-2010.02@new-garb/gems/garb-0.9.1/lib/garb/management/goal.rb:24:in `for_profile'
from /Users/sean/.rvm/gems/ree-1.8.7-2010.02@new-garb/gems/garb-0.9.1/lib/garb/management/profile.rb:40:in `goals'
from (irb):30
```

I see the same behavior for accounts (account.goals).

I'm still tracing the code, but I wanted to put this here sooner rather than later in case others had this issue.

**Comment by tpitale** [comment]
Can you show me the code you used before profile.goals. This may indicate that you do not have any goals defined for that account.

Let me know and I'll take a look asap.

**Comment by tpitale** [comment]
I haven't heard back, closing the issue.

**Comment by seanhussey** [comment]
My apologies.  I reverted after entering the issue and then I couldn't recreate it at all. I figured it must have been a Rails 3 vs. 2.3 issue combined with garb 0.7.6 and 0.9.*.  I meant to explore it more and get back to you, but I was sidetracked.

Again, sorry for wasting your time.  Thanks for keeping an eye on it.
