### ISSUE TITLE
CA_CERT_FILE is undefined in AuthenticationRequest

### ISSUE THREAD

**Issue by stiff** [Fosome/garb#78]
The call `Garb::Session.new.login(login, password, :secure => true)` results in NameError: uninitialized constant Garb::AuthenticationRequest::CA_CERT_FILE at https://github.com/vigetlabs/garb/blob/master/lib/garb/authentication_request.rb#L33

**Comment by tpitale** [comment]
Please read: https://github.com/vigetlabs/garb/wiki/Logging-In under SSL.

**Comment by stiff** [comment]
Oh, thanks.
