### ISSUE TITLE
"Accounts URL did not end in /default"

### ISSUE THREAD

**Issue by aja** [Fosome/garb#8]
very simple example was working before

require 'rubygems'
require 'garb'
require 'postgres'
require 'ruby-debug'
class Analytics
  include Garb::Resource
  Garb::Session.login(username, password)
  Garb::Account.all
end

produces the following

/Library/Ruby/Gems/1.8/gems/garb-0.2.5/lib/garb/data_request.rb:24
raise response.body.inspect unless response.is_a?(Net::HTTPOK)
RuntimeError: "Accounts URL did not end in /default"
method send_request in data_request.rb at line 24
method all  in profile.rb at line 46
method all  in account.rb at line 12
at top level    in analytics.rb at line 8

**Comment by mig** [comment]
fixed in commit 0e81fd10bfd38da471ea4b62b43f5bca18ebfa08
thanks!
