### ISSUE TITLE
What is 'named filters'?

### ISSUE THREAD

**Issue by ckazu** [Fosome/garb#89]
I wrote filters, such as

``` ruby
profile.exits(:filters => {:page_path.eql => '/path/to/page'})
```

and i received under warning:

``` ruby
"The use of SymbolOperator(eql, etc.) has been deprecated. Please use named filters."
```

What is 'named filters'?
How should I write instead of SymbolOperater?

**Comment by tpitale** [comment]
Check out the 'filters' branch, sorry for the premature warnings. Let me know how it works for you.

**Comment by ckazu** [comment]
OK. I understood.
THNX
