### ISSUE TITLE
Does not work in projects using DataMapper

### ISSUE THREAD

**Issue by d11wtq** [Fosome/garb#98]
DataMapper defines operator methods like `#eql` and `#gte` on the `Symbol` class.  Since Garb is trying to define those same methods, things break.  Is there a known workaround for this?

**Comment by tpitale** [comment]
There have been a number of workarounds over the versions. Nothing has been ideal IMO. Which version of Garb are you using? I can suggest something once I know that.

**Comment by d11wtq** [comment]
We're using 0.9.1 and have switched to a workaround using `equals(...)` instead of calling the `#eql` method on the Symbol.  While this silences the error, there is a concern about how Garb may cause low-level bugs in our application, by conflicting with DM.

**Comment by tpitale** [comment]
Garb should not define any of those methods if they are already defined by datamapper. But garb symbol operator style filters obviously do not work, then.

If you'd like you are welcome to try the new filtering branch.

I'll have more in the morning.

**Comment by d11wtq** [comment]
Thanks!  If it's not re-defining the DM then that's ok.  The new filtering branch still defines methods on Symbol, right?

**Comment by tpitale** [comment]
The new filtering branch does at the moment, but provides that functionality for filtering by way of a named-scope-esque interface. More details on that soon.

**Comment by tpitale** [comment]
I've created a shim for DataMapper SymbolOperators. It's in master. Can you try it out and let me know if it works for you? If so I'll release a gem.

**Comment by tpitale** [comment]
Nothing heard from creator.
